Car4U/Models/Status.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Car4U.Models
{
    public class Status
    {
        public int ID { get; set; }
        public string Description { get; set; }


        public virtual ICollection<CarStatus> CarStatus { get; set; }
    }
}

Car4U/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car4U.DAL;
using Car4U.Models;

namespace Car4U.Controllers
{
     [Authorize(Roles = "Admin, Employee")]
    public class StatusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Status
        public ActionResult Index()
        {
            return View(db.Status.ToList());
        }

        // GET: Status/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // GET: Status/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Status/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description")] Status status)
        {
            if (ModelState.IsValid)
            {
                db.Status.Add(status);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(status);
        }

        // GET: Status/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // POST: Status/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description")] Status status)
        {
            if (ModelState.IsValid)
            {
                db.Entry(status).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(status);
        }

        // GET: Status/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Status status = db.Status.Find(id);
            if (status == null)
            {
                return HttpNotFound();
            }
            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Status status = db.Status.Find(id);
            db.Status.Remove(status);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car4U/Views/Status/Create.cshtml
@model Car4U.Models.Status
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="page-header">
        <h2>Criar Estado de Disponibilidade</h2>
    </div>
    <div class="container">
        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="buttonbackoffice">
                        <button class="submit icon-Add" type="submit"> Adicionar </button>
                        <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Status")'"> Voltar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}




@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Car4U/Views/Status/Delete.cshtml
@model Car4U.Models.Status
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Delete";
}

<div class="page-header">
    <h2>Eliminar Estado de Disponibilidade</h2>
</div>

<div class="container">
    <h4>Tem a certeza que pretende apagar este estado de Disponibilidade?</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            <div class="buttonbackoffice">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions">
                        <button class="submit icon-Delete" type="submit" value="Delete"> Apagar </button>
                    </div>
                }
                <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Status")'"> Voltar </button>
            </div>
        </div>
    </div>
</div>

Car4U/Views/Status/Details.cshtml
@model Car4U.Models.Status
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Details";
}

<div class=" page-header">
    <h2>Detalhes do Estado de Disponibilidade</h2>
</div>
<div class="container">
    <div class="form-horizontal">
        <div class="form-group">
            <div class=" col-md-10">
                <div>
                    <h4>
                        Estado: @Html.DisplayFor(model => model.Description)
                    </h4>
                </div>
                <div class="buttonbackoffice">
                    <button class="submit icon-edit" type="button" onclick="location.href='@Url.Action("Edit", "Status", new { id = Model.ID })'"> Editar </button>
                    <button class="submit icon-Delete" type="button" onclick="location.href='@Url.Action("Delete", "Status", new { id = Model.ID })'"> Eliminar </button>
                    <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Status")'"> Voltar </button>
                </div>
            </div>
        </div>
    </div>
</div>

Car4U/Views/Status/Edit.cshtml
@model Car4U.Models.Status
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page-header">
        <h2>Editar Estado de Disponibilidade</h2>
    </div>
    <div class="container">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    <div class="buttonbackoffice">
                        <button class="submit icon-Save" type="submit" value="Save"> Guardar </button>
                        <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Status")'"> Voltar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}



        @*@section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }*@
    

Car4U/Views/Status/Index.cshtml
@model IEnumerable<Car4U.Models.Status>
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Index";
}
<div class="page-header">
    <h2> Estado de Disponibilidade</h2>
</div>

<div class="container col-lg-4">
    <div class="form-group">
        <div class="buttonbackoffice">
            <button class="submit icon-Add" type="button" onclick="location.href='@Url.Action("Create", "Status")'"> Adicionar </button>
        </div>
    </div>
    <table class="table tableheader table-responsive">
        <thead>
            <tr>
                <th>
                    Estado
                    @*@Html.DisplayNameFor(model => model.Description)*@
                </th>
                <th style="font-weight:900;
                    font-size:14px;
                    font-style:oblique" ;>+ Opções</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <div class="iconsbackoffice">
                        @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "icon-edit submit", @title = "Editar" })
                        @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "icon-Details submit", @title = "Detalhes" })
                        @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "icon-Delete submit", @title = "Apagar" })
                    </div>
                </td>
            </tr>
        }
    </table>
</div>