Car4U/Controllers/FuelTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car4U.DAL;
using Car4U.Models;

namespace Car4U.Controllers
{
     [Authorize(Roles = "Admin, Employee")]
    public class FuelTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FuelTypes
        public ActionResult Index()
        {
            return View(db.FuelTypes.ToList());
        }

        // GET: FuelTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FuelType fuelType = db.FuelTypes.Find(id);
            if (fuelType == null)
            {
                return HttpNotFound();
            }
            return View(fuelType);
        }

        // GET: FuelTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FuelTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description")] FuelType fuelType)
        {
            if (ModelState.IsValid)
            {
                db.FuelTypes.Add(fuelType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fuelType);
        }

        // GET: FuelTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FuelType fuelType = db.FuelTypes.Find(id);
            if (fuelType == null)
            {
                return HttpNotFound();
            }
            return View(fuelType);
        }

        // POST: FuelTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description")] FuelType fuelType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fuelType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fuelType);
        }

        // GET: FuelTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FuelType fuelType = db.FuelTypes.Find(id);
            if (fuelType == null)
            {
                return HttpNotFound();
            }
            return View(fuelType);
        }

        // POST: FuelTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FuelType fuelType = db.FuelTypes.Find(id);
            db.FuelTypes.Remove(fuelType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car4U/Views/FuelTypes/Create.cshtml
@model Car4U.Models.FuelType

@{
    ViewBag.Title = "Create";
}
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page-header">
        <h2>Criar Tipo de Combustivel</h2>
    </div>
    <div class="container">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="buttonbackoffice">
                        <button class="submit icon-Add" type="submit"> Adicionar </button>
                        <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "FuelTypes")'"> Voltar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}



Car4U/Views/FuelTypes/Delete.cshtml
@model Car4U.Models.FuelType
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Delete";
}


<div class="page-header">
    <h2>Eliminar tipo de combustivel</h2>
</div>

<div class="container">
    <div class=" form-horizontal">
    <div class="form-group">
            <div class=" col-md-10">
                <h4> Tem a certeza que pretende apagar este tipo de combustivel?</h4>
                <table class=" table tableheader table-responsive" style="width:200px">
                    <tr></tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Description)</td>
                        <td>@Html.DisplayFor(model => model.Description)</td>
                    </tr>
                </table>
            <div class="buttonbackoffice">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions">
                        <button class="submit icon-Delete" type="submit" value="Delete">Apagar</button>
                    </div>
                }
                <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "FuelTypes")'"> Voltar </button>
            </div>
        </div>
    </div>
</div>
</div>


Car4U/Views/FuelTypes/Details.cshtml
@model Car4U.Models.FuelType
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Details";
}

<div class="page-header">
    <h2>Tipo de combustivel</h2>
</div>
<div class="container">
    <div class=" form-horizontal">
        <div class="form-group">
            <div class=" col-md-10">
                <div>
                    <h4> @Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h4>
                </div>
                <div class="buttonbackoffice">
                    <button class="submit icon-edit" type="button" onclick="location.href='@Url.Action("Edit", "FuelTypes", new { id = Model.ID })'"> Editar </button>
                    <button class="submit icon-Delete" type="button" onclick="location.href='@Url.Action("Delete", "FuelTypes", new { id = Model.ID })'">Eliminar</button>
                    <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "FuelTypes")'"> Voltar </button>
                </div>
            </div>
        </div>
    </div>

</div>

Car4U/Views/FuelTypes/Edit.cshtml
@model Car4U.Models.FuelType
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page-header">
        <h2>Tipo de combustivel</h2>
    </div>
    <div class="container">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                    <div class="buttonbackoffice">
                        <button class="submit icon-Save" type="submit" value="Save"> Guardar </button>
                        <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "FuelTypes")'"> Voltar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Car4U/Views/FuelTypes/Index.cshtml
@model IEnumerable<Car4U.Models.FuelType>

@{
    ViewBag.Title = "Index";
}
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<div class="page-header">
    <h2>Tipo de combustivel</h2>
</div>

<div class="container">
    <div class="container col-lg-4">
        <div class="form-group">
            <div class="buttonbackoffice">
                <button class="submit icon-Add" type="button" style="float:left" onclick="location.href='@Url.Action("Create", "FuelTypes")'"> Adicionar </button>
            </div>
        </div>

        <table class="table tableheader table-responsive">
            <thead>
                <tr>
                    <th>  Combustível </th>
                    <th style="font-weight:900;
                    font-size:14px;
                    font-style:oblique" ;>+ Opções</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <div class="iconsbackoffice">
                            @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "icon-edit submit", @title = "Editar" })
                            @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "icon-Details submit", @title = "Detalhes" })
                            @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "icon-Delete submit", @title = "Apagar" })
                        </div>
                    </td>
                </tr>
            }

        </table>


    </div>

</div>