Car4U/Models/Promotion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Car4U.Models
{
    public class Promotion
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int Percentage { get; set; }
        public int Days { get; set; }

        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}

Car4U/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car4U.DAL;
using Car4U.Models;

namespace Car4U.Controllers
{
     [Authorize(Roles = "Admin, Employee")]
    public class PromotionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Promotions
        public ActionResult Index()
        {
            return View(db.Promotions.ToList());
        }

        // GET: Promotions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotion promotion = db.Promotions.Find(id);
            if (promotion == null)
            {
                return HttpNotFound();
            }
            return View(promotion);
        }

        // GET: Promotions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Promotions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Description,Percentage,Days")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                db.Promotions.Add(promotion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(promotion);
        }

        // GET: Promotions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotion promotion = db.Promotions.Find(id);
            if (promotion == null)
            {
                return HttpNotFound();
            }
            return View(promotion);
        }

        // POST: Promotions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Description,Percentage,Days")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(promotion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(promotion);
        }

        // GET: Promotions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotion promotion = db.Promotions.Find(id);
            if (promotion == null)
            {
                return HttpNotFound();
            }
            return View(promotion);
        }

        // POST: Promotions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Promotion promotion = db.Promotions.Find(id);
            db.Promotions.Remove(promotion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car4U/Views/Promotions/Create.cshtml
@model Car4U.Models.Promotion
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()


    <div class="page-header">
        <h2>Criar Promoção</h2>
    </div>
    <div class="container">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Percentage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Percentage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Days, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="buttonbackoffice" style="float: none">
                        <button class="submit icon-Add" type="submit"> Adicionar </button>
                        <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Promotions")'"> Voltar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Car4U/Views/Promotions/Delete.cshtml
@model Car4U.Models.Promotion
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Delete";
}

<div class="page-header">
    <h2>Eliminar Promoção</h2>
</div>
<div class=" container">
    <div class=" form-horizontal">
        <div class="form-group">
            <div class=" col-md-10">
                <h4>Tem a certeza que pretende apagar esta Promoção?</h4>
                <table class=" table tableheader table-responsive" style="width:200px">
                    <tr><td></td><td></td></tr>
                    <tr>
                        <td>Descrição</td>
                        <td>@Html.DisplayFor(model => model.Description)</td>
                    </tr>
                    <tr>
                        <td>Percentagem</td>
                        <td>@Html.DisplayFor(model => model.Percentage)</td>
                    </tr>
                    <tr>
                        <td>Dias de Promoção</td>
                        <td>@Html.DisplayFor(model => model.Days)</td>
                    </tr>
                </table>
                <div class="buttonbackoffice">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-actions">
                            <button class="submit icon-Delete" type="submit" value="Delete"> Apagar </button>
                        </div>
                    }
                    <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Promotions")'"> Voltar </button>
                </div>
            </div>
        </div>
    </div>
</div>

Car4U/Views/Promotions/Details.cshtml
@model Car4U.Models.Promotion
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@{
    ViewBag.Title = "Details";
}

<div class=" page-header">
    <h2> Detalhes Promoções</h2>
</div>
<div class=" container">
    <div class=" form-horizontal">
        <div class="form-group">
            <div class=" col-md-10">

                <table class=" table tableheader table-responsive" style="width:200px">
                    <tr><td></td><td></td></tr>
                    <tr>
                        <td>Descrição</td>
                        <td>@Html.DisplayFor(model => model.Description)</td>
                    </tr>
                    <tr>
                        <td>Percentagem</td>
                        <td>@Html.DisplayFor(model => model.Percentage)</td>
                    </tr>
                    <tr>
                        <td>Dias de Promoção</td>
                        <td>@Html.DisplayFor(model => model.Days)</td>
                    </tr>
                </table>

                <div class="buttonbackoffice">
                    <button class="submit icon-edit" type="button" onclick="location.href='@Url.Action("Edit", "Promotions", new { id = Model.ID })'"> Editar </button>
                    <button class="submit icon-Delete" type="button" onclick="location.href='@Url.Action("Delete", "Promotions", new { id = Model.ID })'"> Eliminar </button>
                    <button class="submit back" type="button" onclick="location.href='@Url.Action("Index", "Promotions")'"> Voltar </button>
                </div>
            </div>
        </div>
    </div>
</div>

Car4U/Views/Promotions/Edit.cshtml
@model Car4U.Models.Promotion
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page-header">
        <h2>Editar Promoção</h2>
    </div>
    <div class="container">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Percentage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Percentage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Percentage, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Days, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Days, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })

                    <div class="buttonbackoffice">
                        <button class="submit icon-Save" type="submit" value="Save"> Guardar </button>
                        <button class="submit icon-back" type="button" onclick="location.href='@Url.Action("Index", "Promotions")'"> Voltar </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

}



@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Car4U/Views/Promotions/Index.cshtml
@model IEnumerable<Car4U.Models.Promotion>
@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
<div class="page-header">
    <h2>Promoções</h2>
</div>

<div class="container col-lg-6">
    <div class="form-group">
        <div class="buttonbackoffice">
            <button class="submit icon-Add" type="button" onclick="location.href='@Url.Action("Create", "Promotions")'"> Adicionar </button>
        </div>
    </div>
    <table class="table tableheader table-responsive">
        <thead>
            <tr>
                <th>Nome</th>
                <th> Percentagem </th>
                <th> Dias </th>
                <th style="font-weight:900;
                    font-size:14px;
                    font-style:oblique" ;>+ Opções</th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Percentage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Days)
                </td>
                <td>
                    <div class="iconsbackoffice">
                        @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "icon-edit submit", @title = "Editar" })
                        @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "icon-Details submit", @title = "Detalhes" })
                        @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "icon-Delete submit", @title = "Apagar" })
                    </div>
                </td>
            </tr>
        }
    </table>
</div>